ADC_WR 	EQU 	P3.5		; ADC WR PIN
ADC_RD 	EQU 	P3.6		; ADC RD PIN
ADC_INT	EQU	P3.4		; ADC INTR PIN

LED	EQU	P2		; OUT PUT
ADC	EQU	P1		; ADC OUT MCU IN
	
	ORG 	00H		; PROGRAM STORE LOCATION

MAIN:	CALL	DELAY
	CALL	CONVERT		; RESULT IS IN A
	MOV	LED, A		; WRITE RESULT TO BAR DISPLAY
	JMP	MAIN

CONVERT:
	SETB	ADC_WR		; ADC WR PIN HIGH
	SETB	ADC_RD		; ADC RD PIN HIGH
	NOP			; NO OPERATION AS A DELAY
	CLR	ADC_WR		; ADC WR PIN LOW
	NOP			; NO OPERATION AS A DELAY
	SETB	ADC_WR		; ADC WR PIN HIGH
	JB	ADC_INT,$	; POLL FOR INTR = 0
	CLR	ADC_RD		; ADC RD PIN LOW
	NOP			; NO OPERATION AS A DELAY
	MOV	A, ADC		; READ ADC PORT IN A
	SETB	ADC_RD		; ADC RD PIN HIGH
	RET			; RETURN FROM ROUTINE

DELAY:				; DELAY SUBROUTINE 
	MOV	R7,#20		;		
L3 :	MOV	R6,#100		;
L2 :	MOV	R5,#100		;
L1 :	DJNZ	R5,L1		;
	DJNZ	R6,L2		;
	DJNZ	R7,L3		;
	RET			; END DELAY SUBROUTINE

	END			; END OF PROGRAM