;====================================================================
; Main.asm file generated by New Project wizard
;
; Project:	 Traffic Light Signal - 8051
; Created:   Sun May 22 2022
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
; Code by:	ElektroSoft Solutions (SMC-Pvt) Ltd
; Website:	www.essol.com.pk
; Contact:	+92-302-8888-920 (WhatsApp/Call)
; Hardware used: 8051 mini Development Board v1.0 (made by ElektroSoft Solutions)
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:	
      ; Write your code here
      MOV P0, #00H
      MOV P1, #00H
      MOV P2, #00H
      MOV P3, #00h
again:
      SETB P2.0			;Red light ON for one bi-directional road
      SETB p2.5			;Green light ON	for second intersecting bi-directional road
      CALL DELAY30		;delay for 30-35 seconds
      CLR P2.0			;OFF Red light for one bi-directional road
      CLR P2.5			;OFF Green light for second intersecting bi-directional road
      SETB P2.1			; Yellow light ON for one bi-directional road
      SETB P2.4			; Yellow light ON for second intersecting bi-directional road
      CALL DELAY15		; delay for 15 second for Yellow light
      CLR P2.1			;OFF Yellow light for one bi-directional road
      CLR P2.4			;OFF Yellow light for second intersecting bi-directional road
      SETB P2.2			;Green light ON for one bi-directional road
      SETB P2.3			;Red lighit ON for second intersecting bi-directional road
      CALL DELAY30		;delay for 30-35 seconds
      CLR P2.2			;OFF Green light for one bi-directional road
      CLR P2.3			;OFF Red lighit for second intersecting bi-directional road
      
      CLR P2.0			;OFF Red light for one bi-directional road
      CLR P2.5			;OFF Green light for second intersecting bi-directional road
      SETB P2.1			; Yellow light ON for one bi-directional road
      SETB P2.4			; Yellow light ON for second intersecting bi-directional road
      CALL DELAY15		; delay for 15 second for Yellow light
      
      
      SJMP again		; Repeat the sequence again
      
Loop:	
      jmp Loop
      
DELAY30:				;30-35 seconds delay routine
		MOV R5, #255
HERE1:	MOV R4, #255
HERE2:	MOV R3, #255
HERE3:	DJNZ R3, HERE3
		DJNZ R4, HERE2
		DJNZ R5, HERE1
		RET
		
DELAY15:				;15 seconds delay routine
	    MOV R5, #100
HERE4:	MOV R4, #255
HERE5:	MOV R3, #255
HERE6:	DJNZ R3, HERE6
		DJNZ R4, HERE5
		DJNZ R5, HERE4
		RET

;======================
      END
