
	ORG	00H		; PROGRAM STORE LOCATION
	MOV	P0,#00H		; REFRESHING PORT-0
	MOV	P1,#00H		; REFRESHING PORT-1
	MOV	P2,#00H		; REFRESHING PORT-2
	MOV	P3,#00H		; REFRESHING PORT-3

AGAIN:	
	CLR	P0.7		; PORT-0 PIN-7 LOW (LED1-ON)
	SETB	P2.0		; PORT-2 PIN-0 HIGH (LED2-ON)
	LCALL   DELAY		; CALL DELAY SUBROUTINE
	SETB	P0.7		; PORT-0 PIN-7 HIGH (LED1-OFF)
	CLR	P2.0		; PORT-2 PIN-0 LOW (LED2-OFF)
	LCALL   DELAY		; CALL DELAY SUBROUTINE
	LJMP	AGAIN		; LOOP FOREVER TO LABEL AGAIN

DELAY:				; DELAY SUBROUTINE 
	MOV	R7,#50		
L3 :	MOV	R6,#100
L2 :	MOV	R5,#100
L1 :	DJNZ	R5,L1
	DJNZ	R6,L2
	DJNZ	R7,L3
	RET			; END DELAY SUBROUTINE

	END